POST http://localhost:3000/novoAlunos
Content-Type: application/json

{
    "nome": "Joel",
    "turma": "3º ano info",
    "email": "test@gmail.com",
    "genero": "M",
    "data_nascimento": "2000/04/05"
}

###

GET http://localhost:3000/listarAlunos

###

GET http://localhost:3000/buscarAlunos/7

###

POST http://localhost:3000/alterarAlunos/1
Content-Type: application/json

{
    "nome": "Joel",
    "turma": "3º ano info",
    "email": "test@gmail.com",
    "genero": "M",
    "data_nascimento": "2000/04/05"
}

###
DELETE http://localhost:3000/excluirAlunos/8